version: '3.1'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - frontend
    depends_on:
      - flask

  flask:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:5000 --workers 4 --timeout 0 "main:create_app()"
    volumes:
      - ./app:/var/www
    networks:
      - frontend

networks:
  frontend:
    driver: bridge